export  const CREATE_COUPON_REQUEST = "CREATE_COUPON_REQUEST"
export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS"
export const CREATE_COUPON_FAIL = "CREATE_COUPON_FAIL"

export const GET_ALL_COUPON_REQUEST = "GET_ALL_COUPON_REQUEST"
export const GET_ALL_COUPON_SUCCESS = "GET_ALL_COUPON_SUCCESS"
export const GET_ALL_COUPON_FAIL = "GET_ALL_COUPON_FAIL"

export const DELETE_REQUEST = "DELETE_REQUEST"
export const DELETE_SUCCESS = "DELETE_SUCCESS"
export const DELETE_FAIL = "DELETE_FAIL"

export const UPDATE_COUPON_REQUEST = "UPDATE_COUPON_REQUEST";
export const UPDATE_COUPON_SUCCESS = "UPDATE_COUPON_SUCCESS";
export const UPDATE_COUPON_FAIL = "UPDATE_COUPON_FAIL";
